# Generated by Django 3.0.3 on 2020-09-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=250)),
                ('description', models.CharField(default='', max_length=250)),
                ('state', models.CharField(default='', max_length=250)),
                ('prority', models.IntegerField(default=0)),
            ],
        ),
    ]
