# Generated by Django 3.0.3 on 2020-10-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20201007_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
    ]
